Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 1085, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 552, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 846, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 748, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from openfisca_us import IndividualSim
import pandas as pd
import plotly.express as px

sim = IndividualSim(year=2022)
sim.add_person(
    is_pregnant = True,
    is_wic_at_nutritional_risk = True
)

round(sim.calc("wic")[0] / 12)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mVariableNotFoundError[0m                     Traceback (most recent call last)
[0;32m/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/openfisca_core/simulations/simulation_builder.py[0m in [0;36minit_variable_values[0;34m(self, entity, instance_object, instance_id)[0m
[1;32m    353[0m             [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 354[0;31m                 [0mentity[0m[0;34m.[0m[0mcheck_variable_defined_for_entity[0m[0;34m([0m[0mvariable_name[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    355[0m             [0;32mexcept[0m [0mValueError[0m [0;32mas[0m [0me[0m[0;34m:[0m  [0;31m# The variable is defined for another entity[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/openfisca_core/entities/entity.py[0m in [0;36mcheck_variable_defined_for_entity[0;34m(self, variable_name)[0m
[1;32m     30[0m     [0;32mdef[0m [0mcheck_variable_defined_for_entity[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mvariable_name[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 31[0;31m         [0mvariable_entity[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0mget_variable[0m[0;34m([0m[0mvariable_name[0m[0;34m,[0m [0mcheck_existence[0m [0;34m=[0m [0;32mTrue[0m[0;34m)[0m[0;34m.[0m[0mentity[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     32[0m         [0;31m# Should be this:[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/openfisca_core/entities/entity.py[0m in [0;36mget_variable[0;34m(self, variable_name, check_existence)[0m
[1;32m     27[0m     [0;32mdef[0m [0mget_variable[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mvariable_name[0m[0;34m,[0m [0mcheck_existence[0m [0;34m=[0m [0;32mFalse[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 28[0;31m         [0;32mreturn[0m [0mself[0m[0;34m.[0m[0m_tax_benefit_system[0m[0;34m.[0m[0mget_variable[0m[0;34m([0m[0mvariable_name[0m[0;34m,[0m [0mcheck_existence[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     29[0m [0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/openfisca_core/taxbenefitsystems/tax_benefit_system.py[0m in [0;36mget_variable[0;34m(self, variable_name, check_existence)[0m
[1;32m    298[0m         [0;32mif[0m [0;32mnot[0m [0mfound[0m [0;32mand[0m [0mcheck_existence[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 299[0;31m             [0;32mraise[0m [0mVariableNotFoundError[0m[0;34m([0m[0mvariable_name[0m[0;34m,[0m [0mself[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    300[0m         [0;32mreturn[0m [0mfound[0m[0;34m[0m[0;34m[0m[0m

[0;31mVariableNotFoundError[0m: You tried to calculate or to set a value for variable 'is_wic_at_nutritional_risk', but it was not found in the loaded tax and benefit system (openfisca-us@0.29.0).
Are you sure you spelled 'is_wic_at_nutritional_risk' correctly?
If this code used to work and suddenly does not, this is most probably linked to an update of the tax and benefit system.
Look at its changelog to learn about renames and removals and update your code. If it is an official package,
it is probably available on <https://github.com/openfisca/openfisca-us/blob/master/CHANGELOG.md>.

During handling of the above exception, another exception occurred:

[0;31mSituationParsingError[0m                     Traceback (most recent call last)
[0;32m/tmp/ipykernel_2157/200679985.py[0m in [0;36m<module>[0;34m[0m
[1;32m      9[0m )
[1;32m     10[0m [0;34m[0m[0m
[0;32m---> 11[0;31m [0mround[0m[0;34m([0m[0msim[0m[0;34m.[0m[0mcalc[0m[0;34m([0m[0;34m"wic"[0m[0;34m)[0m[0;34m[[0m[0;36m0[0m[0;34m][0m [0;34m/[0m [0;36m12[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/openfisca_tools/hypothetical.py[0m in [0;36mcalc[0;34m(self, var, period, target, index)[0m
[1;32m    159[0m         """
[1;32m    160[0m         [0;32mif[0m [0;32mnot[0m [0mhasattr[0m[0;34m([0m[0mself[0m[0;34m,[0m [0;34m"simulation"[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 161[0;31m             [0mself[0m[0;34m.[0m[0mbuild[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    162[0m         [0mperiod[0m [0;34m=[0m [0mperiod[0m [0;32mor[0m [0mself[0m[0;34m.[0m[0myear[0m[0;34m[0m[0;34m[0m[0m
[1;32m    163[0m         [0mentity[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0msystem[0m[0;34m.[0m[0mvariables[0m[0;34m[[0m[0mvar[0m[0;34m][0m[0;34m.[0m[0mentity[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/openfisca_tools/hypothetical.py[0m in [0;36mbuild[0;34m(self)[0m
[1;32m     46[0m     [0;32mdef[0m [0mbuild[0m[0;34m([0m[0mself[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m     47[0m         self.simulation = self.sim_builder.build_from_entities(
[0;32m---> 48[0;31m             [0mself[0m[0;34m.[0m[0msystem[0m[0;34m,[0m [0mself[0m[0;34m.[0m[0msituation_data[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     49[0m         )
[1;32m     50[0m         [0mself[0m[0;34m.[0m[0msimulation[0m[0;34m.[0m[0mtrace[0m [0;34m=[0m [0;32mTrue[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/openfisca_core/simulations/simulation_builder.py[0m in [0;36mbuild_from_entities[0;34m(self, tax_benefit_system, input_dict)[0m
[1;32m     97[0m                 'No {0} found. At least one {0} must be defined to run a simulation.'.format(tax_benefit_system.person_entity.key))
[1;32m     98[0m [0;34m[0m[0m
[0;32m---> 99[0;31m         [0mpersons_ids[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0madd_person_entity[0m[0;34m([0m[0msimulation[0m[0;34m.[0m[0mpersons[0m[0;34m.[0m[0mentity[0m[0;34m,[0m [0mpersons_json[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    100[0m [0;34m[0m[0m
[1;32m    101[0m         [0;32mfor[0m [0mentity_class[0m [0;32min[0m [0mtax_benefit_system[0m[0;34m.[0m[0mgroup_entities[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/openfisca_core/simulations/simulation_builder.py[0m in [0;36madd_person_entity[0;34m(self, entity, instances_json)[0m
[1;32m    242[0m         [0;32mfor[0m [0minstance_id[0m[0;34m,[0m [0minstance_object[0m [0;32min[0m [0minstances_json[0m[0;34m.[0m[0mitems[0m[0;34m([0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    243[0m             [0mhelpers[0m[0;34m.[0m[0mcheck_type[0m[0;34m([0m[0minstance_object[0m[0;34m,[0m [0mdict[0m[0;34m,[0m [0;34m[[0m[0mentity[0m[0;34m.[0m[0mplural[0m[0;34m,[0m [0minstance_id[0m[0;34m][0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 244[0;31m             [0mself[0m[0;34m.[0m[0minit_variable_values[0m[0;34m([0m[0mentity[0m[0;34m,[0m [0minstance_object[0m[0;34m,[0m [0mstr[0m[0;34m([0m[0minstance_id[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    245[0m [0;34m[0m[0m
[1;32m    246[0m         [0;32mreturn[0m [0mself[0m[0;34m.[0m[0mget_ids[0m[0;34m([0m[0mentity[0m[0;34m.[0m[0mplural[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/openfisca_core/simulations/simulation_builder.py[0m in [0;36minit_variable_values[0;34m(self, entity, instance_object, instance_id)[0m
[1;32m    356[0m                 [0;32mraise[0m [0mSituationParsingError[0m[0;34m([0m[0mpath_in_json[0m[0;34m,[0m [0me[0m[0;34m.[0m[0margs[0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    357[0m             [0;32mexcept[0m [0mVariableNotFoundError[0m [0;32mas[0m [0me[0m[0;34m:[0m  [0;31m# The variable doesn't exist[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 358[0;31m                 [0;32mraise[0m [0mSituationParsingError[0m[0;34m([0m[0mpath_in_json[0m[0;34m,[0m [0mstr[0m[0;34m([0m[0me[0m[0;34m)[0m[0;34m,[0m [0mcode[0m [0;34m=[0m [0;36m404[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    359[0m [0;34m[0m[0m
[1;32m    360[0m             [0minstance_index[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0mget_ids[0m[0;34m([0m[0mentity[0m[0;34m.[0m[0mplural[0m[0;34m)[0m[0;34m.[0m[0mindex[0m[0;34m([0m[0minstance_id[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mSituationParsingError[0m: {'people': {'person_1': {'is_wic_at_nutritional_risk': "You tried to calculate or to set a value for variable 'is_wic_at_nutritional_risk', but it was not found in the loaded tax and benefit system (openfisca-us@0.29.0). Are you sure you spelled 'is_wic_at_nutritional_risk' correctly? If this code used to work and suddenly does not, this is most probably linked to an update of the tax and benefit system. Look at its changelog to learn about renames and removals and update your code. If it is an official package, it is probably available on <https://github.com/openfisca/openfisca-us/blob/master/CHANGELOG.md>."}}}
SituationParsingError: {'people': {'person_1': {'is_wic_at_nutritional_risk': "You tried to calculate or to set a value for variable 'is_wic_at_nutritional_risk', but it was not found in the loaded tax and benefit system (openfisca-us@0.29.0). Are you sure you spelled 'is_wic_at_nutritional_risk' correctly? If this code used to work and suddenly does not, this is most probably linked to an update of the tax and benefit system. Look at its changelog to learn about renames and removals and update your code. If it is an official package, it is probably available on <https://github.com/openfisca/openfisca-us/blob/master/CHANGELOG.md>."}}}

